/*
 *  (c) Copyright 2016-2021 Hewlett Packard Enterprise Development Company LP.
 *
 *  This software is available to you under a choice of one of two
 *  licenses. You may choose to be licensed under the terms of the
 *  GNU Lesser General Public License Version 3, or (at your option)
 *  later with exceptions included below, or under the terms of the
 *  MIT license (Expat) available in COPYING file in the source tree.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef _NVMM_FAM_H_
#define _NVMM_FAM_H_

#include "nvmm_fam_atomic.h"

#ifdef __cplusplus
extern "C" {
#endif

void fam_invalidate(const void *addr, size_t len);

void fam_persist(const void *addr, size_t len);

void *fam_memset_persist(void *pmemdest, int c, size_t len);

void *fam_memcpy(void *dest, const void *src, size_t n);

int fam_memcmp(const void *s1, const void *s2, size_t n);

int64_t fam_read_64(const void *addr);

void fam_read_128(const void *addr, int64_t val[2]);

void fam_fence();

#ifdef __cplusplus
}
#endif

#endif /* _NVMM_FAM_H_ */
