/*
 *  (c) Copyright 2016-2017 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef _NVMM_HRTIME_H_
#define _NVMM_HRTIME_H_

#include <time.h>


namespace nvmm {
namespace internal {


typedef struct timespec HRTime;

static inline HRTime get_hrtime() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
    return ts;
}

static inline size_t diff_hrtime_ns(const HRTime& start, const HRTime& end) {
    return (end.tv_sec - start.tv_sec)*1000000000LLU + end.tv_nsec - start.tv_nsec;
}

static inline size_t diff_hrtime_us(const HRTime& start, const HRTime& end) {
    return diff_hrtime_ns(start, end) / 1000LLU;
}


} // end namespace internal
} // end namespace nvmm

#endif // _NVMM_HRTIME_H_
