/*
 *  (c) Copyright 2016-2021,2023 Hewlett Packard Enterprise Development
 *  Company LP.
 *
 *  This software is available to you under a choice of one of two
 *  licenses. You may choose to be licensed under the terms of the
 *  GNU Lesser General Public License Version 3, or (at your option)
 *  later with exceptions included below, or under the terms of the
 *  MIT license (Expat) available in COPYING file in the source tree.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef NVMM_CONFIG_H
#define NVMM_CONFIG_H

#include <assert.h>
#include <cstddef> // size_t
#include <iostream>
#include <string>

namespace nvmm {

class Config {
  public:
    Config(std::string base = SHELF_BASE_DIR, std::string user = SHELF_USER)
        : ShelfBase(base), ShelfUser(user) {
        if (base.empty())
            ShelfBase = SHELF_BASE_DIR;
        if (user.empty())
            ShelfUser = SHELF_USER;
        Setup();
    }

    ~Config() {}

    int LoadConfigFile(std::string path);
    void PrintConfigFile(std::string path);
    void Print();

    void Setup();

    std::string ShelfBase;
    std::string ShelfUser;

    std::string RootShelfPath;
    std::string EpochShelfPath;
    uint64_t PageSize;
};

// TODO: global instance for now
extern Config config;

} // namespace nvmm

#endif
